# See https://symfony.com/doc/current/email/dev_environment.html
swiftmailer:
    # send all emails to a specific address
    delivery_addresses: ['fake@example.com']
    disable_delivery: true

web_profiler:
    intercept_redirects: true
